### ISSUE TITLE
Changing domain from github.io to .com

### ISSUE THREAD

**Issue by Marc92020** [ScratchNitro/scratchnitro.github.io#2]
I tried forking this repository and tried changing the domain to .com but it didn't work.
So should we try to change it to .com? or leave it as .github.io?

**Comment by Marc92020** [comment]
nevermind. .github.io is fine.

**Comment by JackyBorderCollie** [comment]
I tried it too, didn't work. I guess we need to have a paid domain registered if we want the domain to be .com
